# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.

analyzer:
  exclude:
    - lib/src/components/country_picker_pro2/**
    - example/**
  errors:
    implementation_imports: error
    library_prefixes: error
    prefer_relative_imports: error
    depend_on_referenced_packages: error
    use_build_context_synchronously: ignore
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    prefer_final_locals: error

include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    prefer_single_quotes: true # Uncomment to enable the `prefer_single_quotes` rule
    lines_longer_than_80_chars: false
    prefer_relative_imports: false
    library_prefixes: false
    directives_ordering: true
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    depend_on_referenced_packages: false
    sort_constructors_first: false
    use_key_in_widget_constructors: true
    avoid_init_to_null: true
    prefer_final_locals: true
    unnecessary_this: true
    always_specify_types: false
    avoid_print: true
    implementation_imports: true
    prefer_const_literals_to_create_immutables: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
